"""Paired permutation (randomisation) test.

The null hypothesis for *paired* data is not "relabel which arm each
observation came from" -- the pairing forbids that. It is that within each
pair the sign of the difference is exchangeable:

    H0:  d_i  ~  -d_i   independently for every pair i

so the reference distribution is generated by flipping the sign of each
``d_i = a_i - b_i`` with probability 1/2 and recomputing the statistic. That is
the exact conditional null used by Fisher's randomisation test; the unpaired
label-shuffling version would be wrong here and would over-state the noise.

The two-sided p-value uses the ``(r + 1) / (R + 1)`` convention (Davison &
Hinkley 1997, §4.4.3; Phipson & Smyth 2010), which counts the observed
assignment as one of the draws. It is therefore never exactly zero -- an
important property, since a p-value of 0.0 is not something a Monte-Carlo test
of R draws can ever license, and downstream Benjamini-Hochberg and gating code
would happily propagate the impossible number.
"""

from __future__ import annotations

from typing import Sequence

import numpy as np

from proxygap.rng import gen

__all__ = ["paired_permutation"]

_MAX_CELLS = 4_000_000


def _as_vector(x: Sequence[float]) -> np.ndarray:
    return np.asarray(x, dtype=float).reshape(-1)


def _finite(x: np.ndarray) -> np.ndarray:
    """Drop non-finite differences before anything is compared.

    This is not cosmetic. ``NaN >= NaN`` is False, so a NaN observed statistic
    would make *every* randomisation look less extreme than the observation and
    the function would return its floor, ``1 / (n_perm + 1)`` -- a maximally
    significant p-value manufactured out of missing data. Dropping the pair
    matches :func:`proxygap.stats.sequential.evalue_stream`.
    """
    mask = np.isfinite(x)
    return x if bool(mask.all()) else x[mask]


def paired_permutation(
    a: Sequence[float],
    b: Sequence[float],
    seed: int,
    n_perm: int = 10_000,
) -> float:
    """Two-sided p-value for ``mean(a - b) == 0`` under the sign-flip null.

    Returns ``(r + 1) / (n_perm + 1)`` where ``r`` counts sign-flip
    randomisations whose ``|mean|`` is at least the observed ``|mean|``. The
    result lies in ``[1 / (n_perm + 1), 1]``; empty input returns 1.0, and
    pairs whose difference is not finite are dropped.
    """
    va, vb = _as_vector(a), _as_vector(b)
    if va.size != vb.size:
        raise ValueError(f"paired arrays must match in length: {va.size} != {vb.size}")

    d = _finite(va - vb)
    n = int(d.size)
    n_perm = int(n_perm)
    if n == 0 or n_perm < 1:
        return 1.0

    observed = abs(float(d.mean()))
    # Comparisons are ">= observed"; the all-positive sign draw reproduces the
    # observed statistic up to summation order, so allow a relative slack.
    tol = 1e-12 * max(1.0, observed)

    rng = gen(seed)
    chunk = max(1, _MAX_CELLS // max(n, 1))
    at_least = 0
    drawn = 0
    while drawn < n_perm:
        size = min(chunk, n_perm - drawn)
        # Each entry flips sign with probability 1/2, independently.
        signs = 1.0 - 2.0 * rng.integers(0, 2, size=(size, n))
        stats = np.abs((signs * d).mean(axis=1))
        at_least += int(np.count_nonzero(stats >= observed - tol))
        drawn += size

    return float(at_least + 1) / float(n_perm + 1)
